# Generated by Django 4.1.1 on 2022-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_DT', models.PositiveIntegerField(verbose_name='N°_DT')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=20, verbose_name='Prenom')),
                ('equipement', models.CharField(max_length=20, verbose_name='Equipement')),
                ('installation', models.CharField(max_length=20, verbose_name='Installation')),
                ('anomlie', models.TextField(max_length=500, verbose_name='Anomalie')),
                ('service_conserne', models.CharField(max_length=20, verbose_name='Service consernée')),
                ('Status', models.CharField(max_length=20, verbose_name='Action')),
                ('date_creation', models.DateTimeField()),
                ('date_modifie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
