# Generated by Django 4.1.1 on 2022-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0002_alter_work_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_request',
            name='Status',
            field=models.CharField(max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='work_request',
            name='service_conserne',
            field=models.CharField(choices=[('Electrique', 'Electrique'), ('Mecanique', 'Mecanique'), ('Commun', 'Commun')], max_length=20, verbose_name='Service consernée'),
        ),
    ]
