# Generated by Django 4.1.1 on 2022-09-24 20:28

from django.db import migrations, models
import dt.models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0003_alter_work_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_request',
            name='number_DT',
            field=models.PositiveIntegerField(default=dt.models.from_500, verbose_name='N°_DT'),
        ),
    ]
