# Generated by Django 4.1.1 on 2022-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0007_alter_work_request_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100, verbose_name='Nom')),
                ('Last_Name', models.CharField(max_length=100, verbose_name='Prenom')),
                ('Function', models.CharField(max_length=100, verbose_name='Function')),
                ('Service', models.CharField(choices=[('Electrique', 'Electrique'), ('Mecanique', 'Mecanique'), ('Exploitation', 'Exploitation'), ('Securité', 'Securité'), ('BDM', 'BDM')], max_length=20, verbose_name='Service')),
            ],
        ),
        migrations.AlterModelOptions(
            name='work_request',
            options={'verbose_name_plural': 'Demande de travaux'},
        ),
    ]
