# Generated by Django 4.1.1 on 2022-09-29 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustemUserd',
            new_name='CustemUser',
        ),
    ]
